# Generated by Django 4.2.1 on 2023-06-19 10:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
