# Generated by Django 4.2.1 on 2023-06-19 11:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='user/images/default_user.png', max_length=255, verbose_name='profile_image'),
        ),
    ]
